### ISSUE TITLE
Error during ExplainRequestIT test execution

### ISSUE THREAD

**Issue by amottier** [waarp/Waarp-All#113]
I'm trying to build Waarp using Maven 3.9.1 (using Maven wrapper) and OpenJDK 11.0.18 on Debian Bullseye.

I'm running `./mvnw -P jre11 clean install` and get the following error in the log (I can add the full build log if useful):
```
11:42:51.725 [main] WARN  org.waarp.openr66.protocol.junit.TestAbstractMinimal - org.waarp.openr66.protocol.it.ExplainRequestIT.setUp3DbBeforeClass(ExplainRequestIT.java:279) : File /home/antoine/workspace/projects/waarp/Waarp-All/WaarpR66/src/test/resources/it/scenario_big_file_limitbdw/R1/conf/server_1_SQLDB.xml exists? true
11:42:51.726 [main] WARN  org.waarp.openr66.protocol.junit.TestAbstractMinimal - org.waarp.openr66.protocol.it.ExplainRequestIT.setUp3DbBeforeClass(ExplainRequestIT.java:283) : Dir /home/antoine/workspace/projects/waarp/Waarp-All/WaarpR66 exists? true
11:42:51.767 [main] WARN  org.waarp.openr66.protocol.junit.TestAbstractMinimal - org.waarp.openr66.protocol.it.ExplainRequestIT.getServerConfigFile(ExplainRequestIT.java:204) : Build configFile
jdbc:postgresql://localhost:32918/test?loggerLevel=OFF
org.postgresql.Driver
postgresql
11:42:51.779 [main] WARN  org.waarp.openr66.protocol.junit.TestAbstractMinimal - org.waarp.openr66.protocol.it.ExplainRequestIT.getServerConfigFile(ExplainRequestIT.java:256) : Config file created at /tmp/R66/scenario_big_file_limitbdw/R1/conf/server.xml
11:42:51.780 [main] WARN  org.waarp.openr66.protocol.junit.TestAbstractMinimal - org.waarp.openr66.protocol.it.ExplainRequestIT.getServerConfigFile(ExplainRequestIT.java:260) : Copy from /tmp/R66/scenario_big_file_limitbdw/R1/conf/server.xml to /tmp/config.xml
11:42:51.781 [main] WARN  org.waarp.openr66.protocol.junit.TestAbstractMinimal - org.waarp.openr66.protocol.it.ExplainRequestIT.getServerConfigFile(ExplainRequestIT.java:264) : Copy from /tmp/R66/scenario_big_file_limitbdw/R1/conf/server.xml to /tmp/config.xml and return /tmp/R66/scenario_big_file_limitbdw/R1/conf/server.xmlExplainRequestIT
11:42:51.781 [main] WARN  org.waarp.openr66.protocol.junit.TestAbstractMinimal - org.waarp.openr66.protocol.it.ExplainRequestIT.setUp3DbBeforeClass(ExplainRequestIT.java:290) : Config file found /tmp/R66/scenario_big_file_limitbdw/R1/conf/server.xml
11:42:51.782 [main] WARN  org.waarp.openr66.protocol.junit.TestAbstractMinimal - org.waarp.openr66.protocol.it.ExplainRequestIT.setUp3DbBeforeClass(ExplainRequestIT.java:308) : Could not find /tmp/config.xml or /tmp/R66/scenario_big_file_limitbdw/R1/conf/server.xml
11:42:51.782 [main] WARN  org.waarp.openr66.protocol.junit.TestAbstractMinimal - org.waarp.openr66.protocol.it.ExplainRequestIT.initiateDb(ExplainRequestIT.java:327) : File /tmp/R66/scenario_big_file_limitbdw/R1/conf/server.xml exists? true
11:42:51.783 [main] WARN  org.waarp.openr66.protocol.junit.TestAbstractMinimal - org.waarp.openr66.protocol.it.ExplainRequestIT.initiateDb(ExplainRequestIT.java:330) : File /home/antoine/workspace/projects/waarp/Waarp-All/WaarpR66/src/test/resources/it/scenario_big_file_limitbdw/OpenR66-authent.xml exists? true
ERROR org.waarp.openr66.server.ServerInitDatabase  /tmp/R66/scenario_big_file_limitbdw/R1/conf/server.xml -initdb -dir /home/antoine/workspace/projects/waarp/Waarp-All/WaarpR66/src/test/resources/it/scenario_big_file_limitbdw/R1/conf -auth /home/antoine/workspace/projects/waarp/Waarp-All/WaarpR66/src/test/resources/it/scenario_big_file_limitbdw/OpenR66-authent.xml return code: 1 pid: 99999999
11:42:52.304 [main] WARN  org.waarp.openr66.protocol.configuration.Configuration - org.waarp.openr66.protocol.configuration.Configuration.setTransferGuid(Configuration.java:2665) : Startup: Transfer Id will use SQL Sequence
11:42:52.334 [main] WARN  org.waarp.openr66.protocol.junit.TestAbstractMinimal - org.waarp.openr66.protocol.it.ExplainRequestIT.initiateDb(ExplainRequestIT.java:327) : File /home/antoine/workspace/projects/waarp/Waarp-All/WaarpR66/target/test-classes/it/scenario_big_file_limitbdw/R2/conf/server_2.xml exists? true
11:42:52.335 [main] WARN  org.waarp.openr66.protocol.junit.TestAbstractMinimal - org.waarp.openr66.protocol.it.ExplainRequestIT.initiateDb(ExplainRequestIT.java:330) : File /home/antoine/workspace/projects/waarp/Waarp-All/WaarpR66/target/test-classes/it/scenario_big_file_limitbdw/OpenR66-authent.xml exists? true
ERROR org.waarp.openr66.server.ServerInitDatabase  /home/antoine/workspace/projects/waarp/Waarp-All/WaarpR66/target/test-classes/it/scenario_big_file_limitbdw/R2/conf/server_2.xml -initdb -dir /home/antoine/workspace/projects/waarp/Waarp-All/WaarpR66/target/test-classes/it/scenario_big_file_limitbdw/R2/conf -auth /home/antoine/workspace/projects/waarp/Waarp-All/WaarpR66/target/test-classes/it/scenario_big_file_limitbdw/OpenR66-authent.xml return code: 1 pid: 99999999
11:42:52.631 [main] WARN  org.waarp.common.utility.WaarpLoggerListener - org.waarp.common.logging.AbstractWaarpLogger.log(AbstractWaarpLogger.java:168) : 
BUILD SUCCESSFUL
Total time: 0 seconds
Find server file: /home/antoine/workspace/projects/waarp/Waarp-All/WaarpR66/target/test-classes/it/scenario_big_file_limitbdw/R2/conf/server_2.xml
ERROR org.waarp.openr66.server.R66Server  /home/antoine/workspace/projects/waarp/Waarp-All/WaarpR66/target/test-classes/it/scenario_big_file_limitbdw/R2/conf/server_2.xml return code: 0 pid: 390356
11:42:52.912 [main] WARN  org.waarp.openr66.protocol.junit.TestAbstractMinimal - org.waarp.openr66.protocol.it.ExplainRequestIT.startServer(ExplainRequestIT.java:360) : Start Done: 390356
11:42:53.438 [main] ERROR org.waarp.common.database.DbRequest - org.waarp.common.database.DbRequest.select(DbRequest.java:127) : [server1] SQL Exception Request:SELECT * FROM  CONFIGURATION  ERROR: relation "configuration" does not exist
  Position : 16
11:42:53.450 [main] ERROR org.waarp.common.database.DbConstant - org.waarp.common.database.DbConstant.error(DbConstant.java:69) : [server1] SQLException: ERROR: relation "configuration" does not exist
  Position : 16 SQLState: 42P01 VendorError: 0
11:42:53.452 [main] WARN  org.waarp.openr66.configuration.FileBasedConfiguration - org.waarp.openr66.configuration.FileBasedConfiguration.loadDatabase(FileBasedConfiguration.java:1670) : [server1] Database is not yet initiated: run ServerInitDatabase -initdb first : SQL Exception Request:SELECT * FROM  CONFIGURATION 
11:42:54.272 [main] WARN  org.waarp.openr66.configuration.FileBasedConfiguration - org.waarp.openr66.configuration.FileBasedConfiguration.loadServerParam(FileBasedConfiguration.java:491) : [server1] Multiple Monitor configuration unactive
11:42:54.356 [main] ERROR org.waarp.openr66.configuration.FileBasedConfiguration - org.waarp.openr66.configuration.FileBasedConfiguration.setConfigurationServerFromXml(FileBasedConfiguration.java:2324) : [server1] Cannot find Authentication for current host
11:42:54.356 [main] ERROR org.waarp.openr66.server.R66Server - org.waarp.openr66.server.R66Server.initialize(R66Server.java:84) : [server1] Needs a correct configuration file as first argument
11:42:54.357 [main] ERROR org.waarp.openr66.server.R66Server - org.waarp.openr66.server.R66Server.main(R66Server.java:66) : [server1] Cannot start Server OpenR66 for server1
ERROR Cannot start Server OpenR66 for server1
####################### NO R66 SERVER RUNNING ###################
ERROR Exit end of Shutdown
[INFO] Running org.waarp.openr66.protocol.it.ExplainRequestIT
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.023 s <<< FAILURE! - in org.waarp.openr66.protocol.it.ExplainRequestIT
[ERROR] org.waarp.openr66.protocol.it.ExplainRequestIT  Time elapsed: 0.013 s  <<< ERROR!
java.lang.NullPointerException
	at WaarpR66@3.6.2-jre11/org.waarp.openr66.protocol.it.ExplainRequestIT.setUpBeforeClass(ExplainRequestIT.java:189)
	at WaarpR66@3.6.2-jre11/org.waarp.openr66.protocol.it.ExplainRequestIT.setup(ExplainRequestIT.java:152)
```

What is weird is that line `189` in `ExplainRequestIT.java` is `setUpBeforeClassClient();` so I don't understand how it can trigger a `NullPointerException`.

**Comment by fredericBregier** [comment]
I did not had time to inspect but I believe the issue is the one before: Cannot start Server OpenR66 for server1.
configFile might be null then ?

**Comment by amottier** [comment]
I'm attaching my full log from the build: [202304051105-all-clean-install.log](https://github.com/waarp/Waarp-All/files/11198142/202304051105-all-clean-install.log)

I can see:
```
11:42:51.767 [main] WARN  org.waarp.openr66.protocol.junit.TestAbstractMinimal - org.waarp.openr66.protocol.it.ExplainRequestIT.getServerConfigFile(ExplainRequestIT.java:204) : Build configFile
jdbc:postgresql://localhost:32918/test?loggerLevel=OFF
org.postgresql.Driver
postgresql
```

So I'm assuming that configFile is ok.

**Comment by amottier** [comment]
I managed to run the tests. Guess it was related to timing issues as I only run them on a different computer.
So I'm closing this issue.
